version: '3.8'

services:
  app:
    container_name: sadus-bar
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sadus
      SPRING_DATASOURCE_USERNAME: saducao
      SPRING_DATASOURCE_PASSWORD: saducao
    networks:
      - rede

  db:
    image: postgres:15
    container_name: sadus-db
    restart: always
    environment:
      POSTGRES_DB: sadus
      POSTGRES_USER: saducao
      POSTGRES_PASSWORD: saducao
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rede

volumes:
  postgres_data:

networks:
  rede:
